

service: CoordServer # NOTE: update this with your service name


provider:
  name: aws
  runtime: nodejs8.10
  environment:
    tableName: userids
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:us-east-1:899344461848:table/userids"

functions:
  getCoordServer:
    handler: server.getCoordServer
